# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Processes
  items:
    - label: 'Post-conference Follow-up'
      link: '/post-conference-follow-up'
- label: Documentation
  items:
   # - label: 'Creating docs'
   #   link: '/usage/creating-docs'
   # - label: 'Navigation'
    #  link: '/usage/navigation'
    #- label: 'Shadowing' 
     # link: '/usage/shadowing'
    - label: 'Campaigns'
      link: '/campaigns' 
    - label: 'Contacts'
      link: '/contacts' 
    - label: 'Opportunities'
      link: '/opportunities'  
    - label: 'Quoting'
      link: '/quoting'
   # - label: 'test'
    #  link: '/test'